ITEM.name = "Packet of Dimenhydrinate pills"
ITEM.model = "models/carlsmei/escapefromtarkov/medical/analgin.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.desc = "A small pack of Dimenhydrinate, useful for temporarily negating nausea"
ITEM.category = "Medical"
ITEM.price = 50
ITEM.uniqueID = "medical_concusspills"
ITEM.treatString = "Administering Dimenhydrinate pill"
ITEM.treatSound = "npc/barnacle/barnacle_gulp1.wav"
ITEM.concussionTreat = true
ITEM.duration = 60
ITEM.maxSize = 50